### PR TITLE
update js dependancies

### PR DESCRIPTION
**Pull request by thewriteway**
Tested user functionality before and after updates. No breaking changes found.
upgrade jquery to 3.7.1
updated chart js to 3.9.1
update mousetrap to 1.6.5
updated sockjs to 1.6.1

### CODE REVIEW

**Comment by ohawker** [comment]
Hi @thewriteway, can you also upgrade the sockjs dependency to 1.6.1 please?

**Comment by thewriteway** [comment]
> Hi @thewriteway, can you also upgrade the sockjs dependency to 1.6.1 please?

done. no breakages detected. upped to v1.5.2

**Comment by ohawker** [comment]
> Completed.

Many thanks

**Review by kagemomiji — APPROVED** [review]
@thewriteway @ohawker 
Thank you for the great work on this Pull Request. 
I've reviewed the changes and everything looks good with no issues found. 
Your contributions are greatly appreciated!

**Pull request merged**
