### PR TITLE
Support CUE-indexed tracks

### PR DESCRIPTION
**Pull request by mmskv**
Hi, thank you for maintaining airsonic-advanced!

This change is taken from https://github.com/airsonic-advanced/airsonic-advanced/pull/756 pull request by @Yetangitu.
I am not skilled enough in Java to review code, but I did a sanity check and CUE files in my library are indexed as expected.

### Description from the pull request:
---

This change adds support for cue-indexed files. Indexed tracks are added to the database using their relative position in the parent file and are played individually by means of a "split" transcoding which is inserted into the transcoding chain. Base files - the files from which tracks are indexed - are shown or hidden depending on whether the 'Hide cue-indexed files' option (on the Media Folders settings page) is set or not. Cue-indexed tracks are represented in the database by their path and start position. The start position is stored in a new 'start_position' field in the database with a default value of '-1.0' - negative values indicate non-indexed files.

**New settings:**

-   _Media Folders/Hide cue-indexed files_ (boolean): show (unset) or hide (set) cue-indexed base files
-   _Transcoding/Splt options_ (text): options used to split off section of a file for streaming, the default sequence `-ss %o -t %d` targets the default `ffmpeg` converter.
-   _Transcoding/Split command_ (text): command used to split off section of a file for streaming, the default command `ffmpeg %S -i %s -vcodec copy -acodec copy -f %f -` achieves this without transcoding (i.e. lossless) by splitting on frame boundaries.

This is a continuation of the cue-support patch I submitted to the original airsonic (https://github.com/airsonic/airsonic/pull/856) which never got merged. This version has been refactored for airsonic-advanced, rebased on the recently-merged relative paths PR (https://github.com/airsonic-advanced/airsonic-advanced/pull/659), put on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard" to be finally (?) resubmitted as a new PR.

**Database changes:**

-   add column `start_position` (double) default -1.0 (used to identify and access indexed tracks)
-   add column `index_path` varchar (used to store and identify indexed files)
-   drop unique index on path+folder_id
-   add unique index on path+folder_id+start_position

**Configuration changes:**

-   modify the `mp3 audio` transcoder to add the Split options sequence to enable track splitting. The `mp3 audio` transcoder is checked for the presence of the Split options placeholder (`%S`), if this is present the transcoder is not modified.

### CODE REVIEW

**Comment by kagemomiji** [comment]
@mmskv 
Thank you for your PR. 
I tried this branch and could not load cue properly.
I am not familiar with this change, so if there is some special setting, could you please let me know?

**Comment by kagemomiji** [comment]
- [x] bug of detection of update cue sheet
- [x] bug of update tracks from cuesheet after update of cue sheet
- [ ] bug of double count of cue sheet tracks

**Comment by mmskv** [comment]
Hi, looks like this PR is not ready for a merge yet. Even though CUE-indexed tracks can be played fine now, I started getting a ton of errors like these even for albums that do not contain CUE files:

```
2023-02-11 00:16:59.607 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for album org.airsonic.player.domain.Album@6d947e27

java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.updateDocument(org.apache.lucene.index.Term, java.lang.Iterable)" because the return value of "java.util.Map.get(Object)" is null

```
```
2023-02-11 00:18:04.474 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for mediaFile Balcon Sin Flores

java.lang.NullPointerException: null
```
These errors were thrown when starting airsonic with a new database.

> I tried this branch and could not load cue properly.

Sorry for late reply, what do you mean by this? I can provide some CUE-indexed tracks as an example.

**Comment by kagemomiji** [comment]
@mmskv 

Thank you for your feedback. I'm now woking on IndexManager bug.

> Sorry for late reply, what do you mean by this? I can provide some CUE-indexed tracks as an example.

Never mind, I have already solved the problem.

**Comment by kagemomiji** [comment]
@mmskv 

I have fixed scanning problem by PR #113
Do you see tons of errors yet?

**Comment by mmskv** [comment]
Thank you for the fix! Now directories containing dots can be opened and played fine.
Yes, there is a "Failed to create search index" for almost? every mediaFile, artist and album. This only affects search capabilities.

I can't reproduce it by creating an empty /var/music directory and copying couple folders that failed indexing. They index without errors.

Do you have any advice on ways to debug this?

<details>
  <summary>Here is a sample traceback</summary>
  
  ```
2023-02-19 23:24:54.987 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for mediaFile 1991  - '77 Live

java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.updateDocument(org.apache.lucene.index.Term, java.lang.Iterable)" because the return value of "java.util.Map.get(Object)" is null
        at org.airsonic.player.service.search.IndexManager.index(IndexManager.java:140) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:307) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:311) ~[classes/:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:311) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:311) ~[classes/:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:311) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:311) ~[classes/:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
  ```
  
</details>

**Comment by kagemomiji** [comment]
@mmskv 

Before IndexWriter throw error,  an exception must be thrown from the following part.
This PR affects L217-L220.
Please check stacktrace from this part before the first IndexWriter error occurs.

https://github.com/kagemomiji/airsonic-advanced/blob/6db9539c3f714a1991180fec2e06132ca05803d3/airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java#L217-L273

**Comment by mmskv** [comment]
There is an index out of bounds exception thrown in the beginning followed by all the "Failed to create search index" errors.
<details>
```
 <summary>2023-02-20 22:08:13.331 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library </summary>

java.lang.IndexOutOfBoundsException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:219) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$2(MediaScannerService.java:191) ~[classes/:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList.get(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaFileService.createIndexedTracks(MediaFileService.java:754) ~[classes/:na]
	at org.airsonic.player.service.MediaFileService.checkLastModified(MediaFileService.java:230) ~[classes/:na]
	at org.airsonic.player.service.MediaFileService.lambda$16(MediaFileService.java:498) ~[classes/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:503) ~[classes/:na]
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:284) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:310) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:311) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:311) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:311) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:311) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:311) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:311) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:311) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:311) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$6(MediaScannerService.java:219) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	... 5 common frames omitted


```
</details>

**Comment by kagemomiji** [comment]
@mmskv 

thank you.

your error happens the following part L754
From this codes,  `cueSheet.getAllTrackData().get(i + 1)` will not produce indexed out bound exception.
So `.getIndices().get(0)` throws exception.

It occurs when the cue sheet contains the last index track without INDEX field.
Could you check your cue sheets?

I will work for skipping this exception to continue writing the index.

https://github.com/kagemomiji/airsonic-advanced/blob/46229b0d2599a028400efeaeae4990603f85a8c9/airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java#L747-L756

**Comment by kagemomiji** [comment]
@mmskv 

the following PR ignore java.lang.IndexOutOfBoundsException at scanning.
If there is a invalid cue sheet, the latest edge version will show you its path in airsonic.log

https://github.com/kagemomiji/airsonic-advanced/pull/127

**Comment by mmskv** [comment]
Thank You! With #127 library scans fine and errors out on one broken CUE sheet. Still get myriad of "Failed to create search index" errors, will create issue on that later.

**Comment by masterwishx** [comment]
is it working now ?
i having error for CUE , opened discussion....
https://github.com/kagemomiji/airsonic-advanced/discussions/241

image

**Pull request merged**
